Client create collection via http client
ioki-mobility/go-outline pull request #17
Opened 2023-07-19 06:26 UTC by StefMa

Does not fix anything, but is somewhat part of #14 
This adds the support for the HTTP client to *create* a collection.

https://www.getoutline.com/developers#tag/Collections/paths/~1collections.create/post

Only "name" is required, so I added it.
We can later adjust it. Not sure (yet) what the default value for `private` is.
I assume it is `true`, but if not, we should add it to the request and make it later configurable. 

I also fixed a few typos suggested by my IDE :)

2023-07-19 18:47 UTC, rsjethani requested changes
Good work overall! Thanks!
I would also request adding suitable test(s), see other api call related tests

2023-07-19 18:47 UTC, rsjethani commented on collections.go
> +func (cl *CollectionsClient) Create(name CollectionName) *CollectionsCreateClient {
No need to create new type here. Types like `CollectionID` represent something unique hence to differentiate them from regular strings we create new type aliases. But here  the `name` has no other property to separate it from a regular string.

2023-07-19 18:47 UTC, rsjethani commented on collections.go
> +// Do make the actual request for fetching said collection info.
Haha these are not typos. Your IDEs thinks `Do` is an  English auxiliary verb `do`  but here it is a noun so original comment is correct. The same goes for other `Do`s.

2023-07-19 18:47 UTC, rsjethani commented on collections.go
> +		// If there are more than one item in current list then there could be more items remaining to be fetched. In
Yes, this is partial correction, full correction would be:
`If there is more than one item in current...`

2023-07-19 18:47 UTC, rsjethani commented on collections.go
> +// Do make the actual request to create a collection.
make -> makes ;)

2023-07-19 18:47 UTC, rsjethani commented on collections.go
> +		// its intention. If fn still wants to continue the abort further processing in current iteration and
correcting correction:
`// its intention. If fn still wants to continue then we abort...`

2023-07-28 13:23 UTC, StefMa commented
@rsjethani can you please have another look on this so I can continue with the CLI 🙏 🙂

2023-07-28 14:34 UTC, rsjethani approved these changes
Just noting that this new API does not provide a way to provide optional properties for the new collection. We would need a new issue for that later.

2023-07-28 14:36 UTC, merged