Add support for creating a collection [cli]
ioki-mobility/go-outline pull request #33
Opened 2023-08-04 11:05 UTC by StefMa

Fixes #14 

This is just a basic usage of creating a collection.
The only supported option is the required "name".

Optional stuff will be added later.
Reference #29

2023-08-04 22:16 UTC, rsjethani requested changes

2023-08-04 22:16 UTC, rsjethani commented on internal/cli/cli.go
> +				Do(context.Background())
s/collectionName/name/

s/collection/col/
We should try to keep identifiers length proportional to their the scope.

Also, break the method chain onto a multiple lines only when necessary, here it seems to fit a conventional 100-120 line length.

2023-08-04 22:16 UTC, rsjethani commented on internal/cli/cli.go
> +
some cosmetic change:
`fetchCommand` -> `fetchSubCmd` and same for others.

2023-08-05 15:05 UTC, rsjethani requested changes
Apply following changes then we are good to go:
```
diff --git a/internal/cli/cli.go b/internal/cli/cli.go
index 8d8283f..10e5a04 100644
--- a/internal/cli/cli.go
+++ b/internal/cli/cli.go
@@ -24,7 +24,7 @@ func Run() error {
 }
 
 func rootCmd() *cobra.Command {
-       var rootCmd = &cobra.Command{Use: "outline"}
+       rootCmd := &cobra.Command{Use: "outline"}
 
        var apiKeyFlag string
        var baseUrlFlag string
@@ -45,7 +45,7 @@ func collectionCmd(rootCmd *cobra.Command) *cobra.Command {
        fetchSubCmd := collectionCmdFetch(rootCmd)
        collectionCmd.AddCommand(fetchSubCmd)
 
-       createSubCmd := collectionCmdCrate(rootCmd)
+       createSubCmd := collectionCmdCreate(rootCmd)
        collectionCmd.AddCommand(createSubCmd)
 
        return collectionCmd
@@ -73,7 +73,7 @@ func collectionCmdFetch(rootCmd *cobra.Command) *cobra.Command {
                                        return fmt.Errorf("can't get collection with id '%s': %w", colId, err)
                                }
 
-                               b, err := json.Marshal(&col)
+                               b, err := json.Marshal(col)
                                if err != nil {
                                        return fmt.Errorf("failed marshalling collection with id '%s: %w", colId, err)
                                }
@@ -84,7 +84,7 @@ func collectionCmdFetch(rootCmd *cobra.Command) *cobra.Command {
        }
 }
 
-func collectionCmdCrate(rootCmd *cobra.Command) *cobra.Command {
+func collectionCmdCreate(rootCmd *cobra.Command) *cobra.Command {
        return &cobra.Command{
                Use:   "create",
                Short: "Creates a collection",
@@ -107,7 +107,7 @@ func collectionCmdCrate(rootCmd *cobra.Command) *cobra.Command {
                                return fmt.Errorf("can't create collection with name '%s': %w", name, err)
                        }
 
-                       b, err := json.Marshal(&col)
+                       b, err := json.Marshal(col)
                        if err != nil {
                                return fmt.Errorf("failed marshalling collection with name '%s: %w", name, err)
                        }
```

2023-08-05 17:34 UTC, StefMa commented
Applied the changes [here](https://github.com/ioki-mobility/go-outline/pull/33/commits/e5f9e640631a1d7b21c1e91557312cff5fb7d08e) and rebased with `main` 👍

2023-08-06 08:28 UTC, rsjethani approved these changes

2023-08-06 10:40 UTC, merged